version: '3'

services:
  rest-server:
    image: node:16-alpine
    build: .
    ports: 
    - ${PORT}:${PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
       - /logs:/docker/logs
       #       - logs:/docker
    networks:
      - my-net

  postgres:
    build: ./database
    image: 13.5-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
       - /db:/dataB
    networks:
      - my-net


networks:
  my-net:
    name: my-custom-network
    driver: bridge